### ISSUE TITLE
Authorize error

### ISSUE THREAD

**Issue by Magicbob5975** [No3x/MMM-GoogleDocs-Notes#10]
I am currently in the works of creating my first mirror, I have been working on this code for a bit and I have received this error after I followed all the steps on authorizing and have been running into this error:

```
/home/pi/MagicMirror/modules/MMM-GoogleDocs-Notes/authorize.js:43
  const auth = new googleAuth();
               ^

TypeError: googleAuth is not a constructor
    at authorize (/home/pi/MagicMirror/modules/MMM-GoogleDocs-Notes/authorize.js:43:16)
    at /home/pi/MagicMirror/modules/MMM-GoogleDocs-Notes/authorize.js:29:3
    at FSReqCallback.readFileAfterClose [as oncomplete] (internal/fs/read_file_context.js:63:3)
```

what should I do in this scenario?

if you are able to help me out on this that would be amazing.

**Comment by No3x** [comment]
Did you run `npm install`? Which node version?

**Comment by bsj2985** [comment]
The is also my first mirror and I am running into the same issue.  npm install has been run and node version is 16.15.0.  Magicbob5975 did you get this resolved?  If so could you help me out?
