### ISSUE TITLE
"Step 9: Select the application type Other"  No Longer Exists 

### ISSUE THREAD

**Issue by bobey6** [No3x/MMM-GoogleDocs-Notes#12]
Hello,

When configuring the Google side, for Step 9 there is no longer an option to select "Other". In the attached screenshot, I've shown what is now in the drop down menu. Could you provide some feedback on which is the correct one to use? Thank you!

![Application_Type](https://user-images.githubusercontent.com/6521043/123150742-b54a5b80-d430-11eb-9536-e5954fda2718.PNG)

**Comment by Niklas1191** [comment]
Hi, if I remember correct, you can use both UWP and TV's and Limited Input Devices.
Make sure your in production mode and NOT testing, else the auth wont work properly and will reset every 7 days.
