### ISSUE TITLE
Failed to Load Resource

### ISSUE THREAD

**Issue by CurlyQ12391** [No3x/MMM-GoogleDocs-Notes#16]
Hello, I was able to successfully install this module and authorize it with my Google cloud project. However, I am getting the following two errors:

- Failed to load resource: the server responded with a status of 404 (Not Found)    :8080/modules/MMM-G.oogleDoc-Notes.js:1
**I am not sure why there is an extra period in the module name
- error on loading script: modules/MMM-GoogleDoc-Notes/MMM-GoogleDocs-Notes.js    loader.js:194

I am not exactly sure what I am missing in terms of the module set up or MM Config.js file, but I would really appreciate some guidance if you are still active on this <3

**Comment by KawaiiStorm15** [comment]
> Hello, I was able to successfully install this module and authorize it with my Google cloud project. However, I am getting the following two errors:
> 
>     * Failed to load resource: the server responded with a status of 404 (Not Found)    :8080/modules/MMM-G.oogleDoc-Notes.js:1
>       **I am not sure why there is an extra period in the module name
> 
>     * error on loading script: modules/MMM-GoogleDoc-Notes/MMM-GoogleDocs-Notes.js    loader.js:194
> 
> 
> I am not exactly sure what I am missing in terms of the module set up or MM Config.js file, but I would really appreciate some guidance if you are still active on this <3

I notice you haven't recieved a response on this yet, and I don't have an answer for you unfortunately but a question instead and maybe we can puzzle it out together. I didn't get as far as you, and I am wondering what type of OAuth 2.0 Client ID you selected as I am noticing that "Other" is no longer an option in the drop down selection as is stated in the ReadMe. Because of that, I get an access denied error. No worries if you're no longer interested in the project but maybe we can make it work!

**Comment by CurlyQ12391** [comment]
Hey, I did end up just deleting the module and trying something else since I couldn't get it to work. However, for Google Auth I have found the following to work and allow me to authenticate.

Instead of "other" select "web application" instead.

Also, in the downloaded JSON file you might need to change the first line from "web" to "installed". I cannot remember the significance of that ATM, but I remember running across those instructions when I initially had trouble.

Hopefully that works for you!

**Comment by No3x** [comment]
Hi there,
some users did have issue selecting the right OAuth settings but you can find information in the closed issues. There is also a video that shows how to setup the OAuth https://github.com/No3x/MMM-GoogleDocs-Notes/issues/3#issuecomment-625764188.

Regarding the 404: you just need to follow the instructions from the readme. By looking closer to the error message it seems like you cloned to module into MMM-GoogleDoc-Notes insead MMM-GoogleDoc**s**-Notes. 
Regarding the config you just need to copy the sample config from the readme into your config.

**Comment by CurlyQ12391** [comment]
My apologies for the extremely delayed response. Not sure where I went wrong when first cloning this modules but I restarted from scratch and was able to authorize and run the module just fine. Thank you!
