### ISSUE TITLE
Goople Process Changed - please update manual

### ISSUE THREAD

**Issue by W-M-B** [No3x/MMM-GoogleDocs-Notes#24]
Hello,
I liked your module, but I cannot complete the installation process.
in Step 9 your suggest to
```
"Select the Credentials tab, click the Create credentials button and select OAuth client ID.
Select the application type "Other"
```
In my Google Console there is no more "other" . 
I can choose 
- Webapplication
- Android
- Chrome-App
- iOS
- TV or Devices 
- Desktop
- Unversal Windows Platform (UWP)
I tried Desktop and TV ... 
in both cases the sudo command for authentication cannot be completed the code is not showing up (either redirecting to localhost or  
the commandline says
`const redirectUrl = credentials.installed.redirect_uris[0];`

Can you give a hint, or update the readme please?

**Comment by No3x** [comment]
Your downloaded credentials file does not seem to contain the `redirect_uris` properties. Can you please verify that you copied the file to the magic mirror module directory?
I just checked and created the credentials with type `Desktop` and it contains `redirect_uris` then the authorize command can be executed. 

Unfortunately after opening the link in a browser and granting the access to drive there is no code provided anymore since **this authentication flow has been deprecated by google since a while**. As far as I know the mainstream solution is to open the authentication url in a built-in browser that redirects to locally running server to complete the authentication flow. Unfortunately this is an interactive process and in the particular case of a magic mirror I don't know if everybody has a browser installed and input devices connected. There are maybe other ways to authenticate but require research and development - if somebody knows a magic mirror module that solved the same problem please let me know.

**Comment by No3x** [comment]
Got some news! I've just pushed a new branch called "24-goople-process-changed-please-update-manual" https://github.com/No3x/MMM-GoogleDocs-Notes/tree/24-goople-process-changed-please-update-manual. It includes some major updates that I'd love your help testing out.

To give it a spin, follow these simple steps:
1. Make sure you have Node.js >=13.0.0 installed.
2. Checkout the new branch:
`git fetch`
`git checkout 24-goople-process-changed-please-update-manual`
4. Run the following commands:
`npm i`
`node authorize.mjs`
5. Follow the authoritzation steps

Please see the README. I've updated it with the latest instructions and description.
If this approach proves to be stable, I will release it as new default.

**Comment by W-M-B** [comment]
This sounds great. I will try it out .. but I am leaving for vacation so it will take a few days before I can try out.!

**Comment by ml334422** [comment]
What directory do you need to be in to do these steps?

To give it a spin, follow these simple steps:

Make sure you have Node.js >=13.0.0 installed.
Checkout the new branch:
git fetch
git checkout 24-goople-process-changed-please-update-manual
Run the following commands:
npm i
node authorize.mjs
Follow the authoritzation steps

**Comment by ml334422** [comment]
Okay this is really getting frustrating. Every time I follow the steps to try to remove and install Node.js it reverts back to 12.22.12. NVM also does not work, each install fails after 10 minutes of doing various commands.

**Comment by No3x** [comment]
> What directory do you need to be in to do these steps?

the `MMM-GoogleDocs-Notes` directory

> Okay this is really getting frustrating. Every time I follow the steps to try to remove and install Node.js it reverts back to 12.22.12. NVM also does not work, each install fails after 10 minutes of doing various commands.

I do not know why this happens and what system you are on. Nodejs is very popular so you should find a lot of tutorials and guides on how to install it. Generally, it helps to remove the old version first. It's really hard to help with the information given, and it's beyond the scope of this ticket.

**Comment by No3x** [comment]
Is anyone about to test it soon? I would like to bring the fix to the main branch so that new users don't have the problem. It works for me so far, but I would like more test results.

**Comment by W-M-B** [comment]
I will try to test this weekend ..

**Comment by W-M-B** [comment]
Hello,
I tried but failed:
I updated my pi 
deleted the MMM-GoogleDocs-Notes directory
switched to the new branch and installed it (took a while). this looked good.
then I switched to the google authorization before I executed.
`node authorize.mjs`
I did this later.. though and executed it afterwards, but the error was the same.

so the google authentication I followed the online steps in github.
but again when I needed to choose an application "other" was not available (see attachment - German only sorry) 

![2023-09-08 19_04_36-OAuth-Client-ID erstellen – APIs und Dienste – MM2Version3 – Google Cloud Consol](https://github.com/No3x/MMM-GoogleDocs-Notes/assets/46317115/9c2faded-c0eb-4cd9-9998-78d9c8b01d1a)

as no "other" was available I tried Desktop app. created downloaded the json file.
copy/pasted it to the raspberry nano and saved it as `client_secret.json`.
the sudo command resulted in the following error (not surporising somehow as I could not follow your instructions).

```
pi@raspberrypi2:~/MagicMirror/modules/MMM-GoogleDocs-Notes $ sudo -u pi -- node authorize.js
node:internal/modules/cjs/loader:1093
  throw err;
  ^

Error: Cannot find module '/home/pi/MagicMirror/modules/MMM-GoogleDocs-Notes/authorize.js'
    at Module._resolveFilename (node:internal/modules/cjs/loader:1090:15)
    at Module._load (node:internal/modules/cjs/loader:934:27)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:83:12)
    at node:internal/main/run_main_module:23:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
```

then I saw I had to run the `node authorize.mjs` first,
I did this with the following result:
```
Error loading client secret file: SyntaxError: Unexpected non-whitespace character after JSON at position 400
Token stored to /home/pi/.credentials/MMM-GoogleDocs-Notes.json
MMM-GoogleDocs-Notes is authorized.
```
the 2nd sudo command resulted in the same error.

1 questions I would need help with before redoing it a little later:
1. what app type can I choose to find the "other"..
then I will try to repeat the complete process (delete notes module) and use ftp to tranfer the json file to avoid copy/paste errors.

any other recommendation?

**Comment by No3x** [comment]
Hi please use the readme from the branch: https://github.com/No3x/MMM-GoogleDocs-Notes/tree/24-goople-process-changed-please-update-manual 
> Please see Step 9: Select the application type TV and limited Input Devices

Can you please try again?

**Comment by W-M-B** [comment]
TOP!
I got my device certified. 
additional feedback: The orientation in the google API is a little difficult as your description is different to my UI. 
also I had my App in testing first and need to make it public available until it worked.

But it is working and a big improvement. Thank you for your patience. I think good to merge
